# Generated by Django 5.1.4 on 2025-05-23 08:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0025_chatbotquota_is_lifetime_free'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="Description of the action (e.g., 'created staff user', 'created coupon code')", max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the action was performed')),
                ('target_chatbot', models.ForeignKey(blank=True, help_text='Chatbot affected by the action, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.chatbot')),
                ('target_coupon', models.ForeignKey(blank=True, help_text='Coupon code affected by the action, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.couponcode')),
                ('target_plan', models.ForeignKey(blank=True, help_text='Subscription plan affected by the action, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.subscriptionplan')),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Activity Log',
                'verbose_name_plural': 'Admin Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
