# Generated by Django 5.1.4 on 2025-02-27 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='system_prompt',
            field=models.TextField(blank=True, max_length=200000, null=True),
        ),
        migrations.CreateModel(
            name='ChatbotTokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to='registration.chatbot')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
