# Generated by Django 5.1.4 on 2025-03-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_chatbot_system_prompt_chatbottokenusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotquota',
            name='grace_period_days',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='chatbotquota',
            name='is_sending_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
