# Generated by Django 5.1.4 on 2025-03-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_chatbotquota_grace_period_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='whatsapp_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='whatsapp_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='whatsapp_url',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
