# Generated by Django 5.1.4 on 2025-03-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_chatbot_whatsapp_id_chatbot_whatsapp_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='messenger_page_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='messenger_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='messenger_url',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
