# Generated by Django 5.1.4 on 2025-03-20 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_chatbotfaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bubbleBgColor', models.CharField(default='#111827', max_length=7)),
                ('bubbleColor', models.CharField(default='#FAFAFA', max_length=7)),
                ('chatBackgroundColor', models.CharField(default='#FAFAFA', max_length=7)),
                ('chatBorder', models.CharField(default='#E5E7EB', max_length=7)),
                ('headerBackgroundColor', models.CharField(default='#111827', max_length=7)),
                ('headerTextColor', models.CharField(default='#FAFAFA', max_length=7)),
                ('footerBackgroundColor', models.CharField(default='#FAFAFA', max_length=7)),
                ('sendButtonColor', models.CharField(default='#111827', max_length=7)),
                ('sendTextColor', models.CharField(default='#FAFAFA', max_length=7)),
                ('headerText', models.CharField(default='Chat', max_length=50)),
                ('inputBorderColor', models.CharField(default='#D1D5DC', max_length=7)),
                ('placeholderText', models.CharField(default='Type your query...', max_length=100)),
                ('inputTextColor', models.CharField(default='#111827', max_length=7)),
                ('inputBgColor', models.CharField(default='#FAFAFA', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chatbot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='registration.chatbot')),
            ],
            options={
                'verbose_name': 'Chatbot Color',
                'verbose_name_plural': 'Chatbot Colors',
            },
        ),
    ]
