# Generated by Django 5.1.4 on 2025-03-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_chatbotcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotcolor',
            name='answerBackgroundColor',
            field=models.CharField(default='#FAFAFA', max_length=10),
        ),
        migrations.AddField(
            model_name='chatbotcolor',
            name='answerTextColor',
            field=models.CharField(default='#FAFAFA', max_length=10),
        ),
        migrations.AddField(
            model_name='chatbotcolor',
            name='faqBackgroundColor',
            field=models.CharField(default='#FAFAFA', max_length=10),
        ),
        migrations.AddField(
            model_name='chatbotcolor',
            name='faqSectionBackgroundColor',
            field=models.CharField(default='#FAFAFA', max_length=10),
        ),
        migrations.AddField(
            model_name='chatbotcolor',
            name='faqTextColor',
            field=models.CharField(default='#FAFAFA', max_length=10),
        ),
        migrations.AddField(
            model_name='chatbotcolor',
            name='questionBackgroundColor',
            field=models.CharField(default='#FAFAFA', max_length=10),
        ),
        migrations.AddField(
            model_name='chatbotcolor',
            name='questionTextColor',
            field=models.CharField(default='#FAFAFA', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatbotcolor',
            name='bubbleBgColor',
            field=models.CharField(default='#111827', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatbotcolor',
            name='bubbleColor',
            field=models.CharField(default='#FAFAFA', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatbotcolor',
            name='chatBackgroundColor',
            field=models.CharField(default='#FAFAFA', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatbotcolor',
            name='chatBorder',
            field=models.CharField(default='#E5E7EB', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatbotcolor',
            name='footerBackgroundColor',
            field=models.CharField(default='#FAFAFA', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatbotcolor',
            name='headerBackgroundColor',
            field=models.CharField(default='#111827', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatbotcolor',
            name='headerTextColor',
            field=models.CharField(default='#FAFAFA', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatbotcolor',
            name='inputBgColor',
            field=models.CharField(default='#FAFAFA', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatbotcolor',
            name='inputBorderColor',
            field=models.CharField(default='#D1D5DC', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatbotcolor',
            name='inputTextColor',
            field=models.CharField(default='#111827', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatbotcolor',
            name='sendButtonColor',
            field=models.CharField(default='#111827', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatbotcolor',
            name='sendTextColor',
            field=models.CharField(default='#FAFAFA', max_length=10),
        ),
    ]
