# Generated by Django 5.1.4 on 2025-03-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_chatbotcolor_answerbackgroundcolor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='domain_name',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
