# Generated by Django 5.1.4 on 2025-03-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_chatbot_domain_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='verify_token',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
