# Generated by Django 5.1.4 on 2025-03-31 07:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_populate_verify_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='verify_token',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
