# Generated by Django 5.1.4 on 2025-03-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_alter_chatbot_verify_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='domain_name',
            field=models.TextField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
