# Generated by Django 5.1.4 on 2025-04-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_alter_chatbot_domain_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='instagram_page_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='instagram_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='instagram_url',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
