# Generated by Django 5.1.4 on 2025-04-01 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_chatbot_instagram_page_id_chatbot_instagram_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('instagram', 'Instagram')], max_length=20)),
                ('history', models.TextField(default='[]')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.chatbot')),
            ],
            options={
                'unique_together': {('chatbot', 'user_id', 'platform')},
            },
        ),
    ]
