# Generated by Django 5.1.4 on 2025-04-02 07:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_chatbotconversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotAPILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('query', models.TextField(blank=True, null=True)),
                ('query_embeddings', models.BinaryField(blank=True, null=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.chatbot')),
            ],
            options={
                'indexes': [models.Index(fields=['chatbot', 'timestamp'], name='registratio_chatbot_eab97d_idx')],
            },
        ),
    ]
