# Generated by Django 5.1.4 on 2025-04-02 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_chatbotapilog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbotapilog',
            old_name='query_embeddings',
            new_name='query_embedding',
        ),
    ]
