# Generated by Django 5.1.4 on 2025-04-04 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_couponcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotpaymenttransaction',
            name='coupon_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='registration.couponcode'),
        ),
        migrations.AddField(
            model_name='chatbotpaymenttransaction',
            name='discounted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
