# Generated by Django 5.1.4 on 2025-04-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_chatbotpaymenttransaction_coupon_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='used_by_chatbots',
            field=models.ManyToManyField(blank=True, related_name='used_coupons', to='registration.chatbot'),
        ),
        migrations.AlterField(
            model_name='chatbotpaymenttransaction',
            name='amount',
            field=models.IntegerField(help_text='Amount in NPR (e.g., 5000, 7000, 10000)'),
        ),
    ]
