# Generated by Django 5.1.4 on 2025-04-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_couponcode_used_by_chatbots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotpaymenttransaction',
            name='amount',
            field=models.IntegerField(help_text='Original package amount (5000, 7000, 10000)'),
        ),
        migrations.AlterField(
            model_name='chatbotpaymenttransaction',
            name='discounted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid after discount', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='chatbotpaymenttransaction',
            name='transaction_id',
            field=models.CharField(help_text='Payment portal transaction_code', max_length=255, unique=True),
        ),
    ]
