# Generated by Django 5.1.4 on 2025-04-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_alter_chatbotpaymenttransaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
