# Generated by Django 5.1.4 on 2025-04-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_chatbot_last_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='last_payment_date',
        ),
        migrations.AddField(
            model_name='chatbotquota',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
