# Generated by Django 5.1.4 on 2025-04-22 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_remove_chatbot_last_payment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the subscription plan (e.g., Basic, Pro)', max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly price in NPR (0 for free plans)', max_digits=10)),
                ('message_limit', models.IntegerField(default=5000, help_text='Monthly message quota (0 for unlimited)')),
                ('trial_days', models.IntegerField(default=7, help_text='Trial period in days (0 for no trial)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is available for selection')),
                ('is_lifetime', models.BooleanField(default=False, help_text='If true, chatbots on this plan have unlimited messages and no expiry')),
                ('auto_reset_quota', models.BooleanField(default=False, help_text='If true, quota resets monthly for free plans')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
            },
        ),
        migrations.RemoveField(
            model_name='chatbotquota',
            name='message_limit',
        ),
        migrations.AddField(
            model_name='chatbotquota',
            name='temporary_message_boost',
            field=models.IntegerField(default=0, help_text='Temporary message boost that resets at cycle end'),
        ),
        migrations.AlterField(
            model_name='chatbotpaymenttransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Original plan price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='chatbotpaymenttransaction',
            name='discounted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='chatbotpaymenttransaction',
            name='transaction_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='chatbotpaymenttransaction',
            name='subscription_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='registration.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='chatbotquota',
            name='subscription_plan',
            field=models.ForeignKey(help_text='Current subscription plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotas', to='registration.subscriptionplan'),
        ),
    ]
