# Generated by Django 5.1.4 on 2025-04-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_subscriptionplan_remove_chatbotquota_message_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotquota',
            name='is_lifetime_free',
            field=models.BooleanField(default=False, help_text='If true, chatbot has unlimited messages without a plan'),
        ),
    ]
