# Generated by Django 5.1.4 on 2025-05-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_chatbotquota_is_lifetime_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
