# Generated by Django 5.1.4 on 2025-05-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_subscriptionplan_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_enterprise',
            field=models.BooleanField(default=False),
        ),
    ]
