# Generated by Django 5.1.4 on 2025-05-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0027_customuser_is_enterprise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_enterprise',
        ),
        migrations.AddField(
            model_name='organization',
            name='is_enterprise',
            field=models.BooleanField(default=False),
        ),
    ]
