# Generated by Django 5.1.4 on 2025-05-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0029_organization_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage for enterprise organizations', max_digits=5),
        ),
    ]
